# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
pr:
  - master
pool:
  vmImage: "vs2017-win2016"

steps:
  - task: PowerShell@2
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/ci.ps1'
      pwsh: true
    env:
      AUTOMATOR_TEST_SUITE_ID: $(TESTSUITEID)
      AUTOMATOR_TOKEN: $(TOKEN)
