matrix:
  include:
    - language: bash
      os: linux
      dist: bionic
      sudo: false
      addons:
        apt:
          packages:
            - jq
            - shellcheck
      before_script: shellcheck ./ci.sh
      script: ./ci.sh