name: Node test

on:
  push:
    branches:
      - master
      - develop
    paths:
      - "azure-devops-extension/run-automator-build-task/**"
      - .github/workflows/node.js.yml
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "azure-devops-extension/run-automator-build-task/**"
      - .github/workflows/node.js.yml

jobs:
  node-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: azure-devops-extension/run-automator-build-task
      - name: Build
        run: yarn build
        working-directory: azure-devops-extension/run-automator-build-task
      - name: Test
        run: yarn test
        working-directory: azure-devops-extension/run-automator-build-task
